-- Seed data for PROMPT.OS
-- Run this in Supabase SQL Editor after creating the prompts table

insert into prompts (id, title, description, full_prompt, category, model, likes, views_count, runs_count, is_trending_now, tags, image_url, creator_name, creator_avatar) values

('cinematic-rain-cityscape',
 'Cinematic Rain Cityscape',
 'A high-end cinematic visualization of a futuristic neon city under heavy rain, with vibrant reflections of magenta and cyan on wet asphalt.',
 'Cinematic drone shot of a futuristic neon city under heavy rain, vibrant reflections of magenta and cyan on wet asphalt, volumetric lighting, photorealistic 8k octane render --ar 16:9',
 'video', 'gpt4', 2400, '12.8k', '5.2k', true,
 array['Video','GPT-4','Cinematic'],
 'https://lh3.googleusercontent.com/aida-public/AB6AXuBe6wR3UeK61Ornh69exDJqZmpGTykt-ISEpI3rZO2T1Srz46FP4e6sXn5i1mJuVI2AaKGiszk7U2gR1N1SztfKpA7nFT80buYu4awH1T5QuLZBkdU10WqizNu8wosnT5g1VDS6Wx7iCztbSckbc5-5E5rlHvoeLRKicHf7ojrT8aoY3ny8DY_HLjh_pmEnVtouB8phIVZQfniTwSoG7n5hwQEd50kBCbbOLXaht4qpSli6Kkgqb72i7j39EGnLu3CC52bybHO8eRk',
 'PROMPT.OS Architect',
 'https://lh3.googleusercontent.com/aida-public/AB6AXuDmuUirJHpRCeIepCurZyWxJshLsHRVOLjmG9hQeQpZgWxm0f-LuLdiDSCITmti5CBP6SRzMdgSyXp4AheHxJYlRtTEtupWEGkBcMieQdaEu_Pia2gMBuA10S9o3z9Dcp5TmVFv0fJfP49U0FPIfoox0c5CwIE9meh3kLL0HUTr57Hruo9xmK5e2FsDovZK1EV-pnEckUoeDkRcfJEjqjzgE3xSfuASd-r9YCZr7BJ-ODNRSiCLt5LJ1bhcO_mIjOPZD1lu3gj_PQ8'),

('neural-topology-shader',
 'Neural Topology Shader',
 'An interactive real-time shader prompt generating glowing neural nodes and flowing topological energy fields.',
 'Real-time GLSL shader of glowing neural nodes, intricate topological energy grid, cyan and purple bloom reflections, 60fps interactive graphics',
 'image', 'nano', 1900, '8.2k', '3.8k', true,
 array['Interactive','Nano Banana','GLSL'],
 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
 'ShaderLab',
 'https://lh3.googleusercontent.com/aida-public/AB6AXuDmuUirJHpRCeIepCurZyWxJshLsHRVOLjmG9hQeQpZgWxm0f-LuLdiDSCITmti5CBP6SRzMdgSyXp4AheHxJYlRtTEtupWEGkBcMieQdaEu_Pia2gMBuA10S9o3z9Dcp5TmVFv0fJfP49U0FPIfoox0c5CwIE9meh3kLL0HUTr57Hruo9xmK5e2FsDovZK1EV-pnEckUoeDkRcfJEjqjzgE3xSfuASd-r9YCZr7BJ-ODNRSiCLt5LJ1bhcO_mIjOPZD1lu3gj_PQ8'),

('luxury-concierge-ui-kit',
 'Luxury Concierge UI Kit',
 'A pristine, minimalist web interface design for a luxury AI concierge service featuring expansive white space and glassmorphism.',
 'Pristine minimalist web interface for luxury AI concierge service, glassmorphic sidebar, muted charcoal and electric violet accents, UI/UX portfolio style --ar 16:9',
 'web', 'geminiPro', 3100, '15.5k', '7.1k', true,
 array['Web','Gemini Pro','UI Kit'],
 'https://lh3.googleusercontent.com/aida-public/AB6AXuDu_R9qG22yly6qulG2WDo2sHmYt2BZrfK-J0TQYMEpkrABnvHEGhe8otCyYYA8myljj1lPjnnuL9seAsSyiOquFiBY8f4cpJ9mNuMYWEHHh_cIAlOvxtqFAJCnnS2XcWCqRAl4wPqDsH6j3fLWk6OHIBJ3E2OeNPJEQO9nR-bVA8tsNu7ocvDpJO2AhdLykoi6ReSiNGTbtjWDieWDjmWM2_zqTmBe7uJE8Fh_rJFB6PEhLxn8yQmeH9vqCUGcY0dxr0prHk38YcU',
 'Concierge Studio',
 'https://lh3.googleusercontent.com/aida-public/AB6AXuDmuUirJHpRCeIepCurZyWxJshLsHRVOLjmG9hQeQpZgWxm0f-LuLdiDSCITmti5CBP6SRzMdgSyXp4AheHxJYlRtTEtupWEGkBcMieQdaEu_Pia2gMBuA10S9o3z9Dcp5TmVFv0fJfP49U0FPIfoox0c5CwIE9meh3kLL0HUTr57Hruo9xmK5e2FsDovZK1EV-pnEckUoeDkRcfJEjqjzgE3xSfuASd-r9YCZr7BJ-ODNRSiCLt5LJ1bhcO_mIjOPZD1lu3gj_PQ8'),

('modular-station-schematic',
 'Modular Station Schematic',
 'A complex 3D isometric diagram of a modular space station, rendered in a clean, schematic style with glowing energy cores.',
 'Complex 3D isometric schematic diagram of modular space station, glowing energy cores, brushed metal textures, dark cosmic background with blue and orange accent lighting',
 'image', 'gpt4', 982, '4.3k', '2.1k', true,
 array['Image','GPT-4','3D Schematic'],
 'https://lh3.googleusercontent.com/aida-public/AB6AXuCy6Fk0LBdlO22HUNIT9XtGvWLo8k0FxI2A_8d9wcyJq2WNPbJ47vrilKl1YOLoR7P7zg0XUvnfCvWkxepgDtee9hzlTpg1--QZPdgTVHeITM1mTHecAIAtSwkzjSlRCgVyaa-M3Wjo1eu4mcGpHyowafam_abJE-ovzdZgwaPk32tyUvk3aU0wC2eU0XQtPQ9cveCG9bwv3PM1rt_thabh6vXGdpIFIyoJFFSsD8QQRvvH6arqTueg7hu0exGrTLGSlyvckICtLbY',
 'AstroTech',
 'https://lh3.googleusercontent.com/aida-public/AB6AXuDmuUirJHpRCeIepCurZyWxJshLsHRVOLjmG9hQeQpZgWxm0f-LuLdiDSCITmti5CBP6SRzMdgSyXp4AheHxJYlRtTEtupWEGkBcMieQdaEu_Pia2gMBuA10S9o3z9Dcp5TmVFv0fJfP49U0FPIfoox0c5CwIE9meh3kLL0HUTr57Hruo9xmK5e2FsDovZK1EV-pnEckUoeDkRcfJEjqjzgE3xSfuASd-r9YCZr7BJ-ODNRSiCLt5LJ1bhcO_mIjOPZD1lu3gj_PQ8'),

('mechanical-metamorphosis',
 'Mechanical Metamorphosis',
 'Macro photography of a mechanical butterfly made from gears, vintage watch parts, and iridescent crystal wings.',
 'Macro photography of mechanical butterfly made from gears, vintage watch parts, and iridescent crystal wings, dark mahogany library bokeh background, warm bronze and gold tones --v 6.0',
 'image', 'midjourneyV6', 4500, '22.1k', '11.4k', true,
 array['Image','Midjourney v6','Macro'],
 'https://lh3.googleusercontent.com/aida-public/AB6AXuD7-uxMpQyn2qVT-NxqAqx1Ig8ZsVPWvrwDa-WWBuqN91CONKseqTpZ67hljGMHOPF3AmijOnVy0rlKAaVa4JeoBEQxlkUIk59jrCZAgeenmeV0u_5sXC-h4bBBcVbGP5cg1Ps7IpWkUEgibzAwAukWUyPQphdg2xIBIXyQTDzvzNTv6Y5N-_73zf5iMCdTJvWNu6QmlbfWDZkcoqZaQd4ErkPe2wV5-d7URKEcsaVCyV2-V4d_z2n4o_HQRASOcHWckGU-npN34Ag',
 'Clockwork AI',
 'https://lh3.googleusercontent.com/aida-public/AB6AXuDmuUirJHpRCeIepCurZyWxJshLsHRVOLjmG9hQeQpZgWxm0f-LuLdiDSCITmti5CBP6SRzMdgSyXp4AheHxJYlRtTEtupWEGkBcMieQdaEu_Pia2gMBuA10S9o3z9Dcp5TmVFv0fJfP49U0FPIfoox0c5CwIE9meh3kLL0HUTr57Hruo9xmK5e2FsDovZK1EV-pnEckUoeDkRcfJEjqjzgE3xSfuASd-r9YCZr7BJ-ODNRSiCLt5LJ1bhcO_mIjOPZD1lu3gj_PQ8'),

('generative-grid-pulse',
 'Generative Grid Pulse',
 'Generative code algorithm creating rhythmic grid pulses, glowing data streams, and reactive canvas nodes.',
 'Algorithmic HTML5 Canvas generative artwork, dynamic grid pulse, reactive neon streams, high contrast dark theme aesthetic',
 'code', 'nano', 1200, '5.6k', '2.8k', true,
 array['Code','Nano Banana','Generative'],
 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80',
 'GridCode Lab',
 'https://lh3.googleusercontent.com/aida-public/AB6AXuDmuUirJHpRCeIepCurZyWxJshLsHRVOLjmG9hQeQpZgWxm0f-LuLdiDSCITmti5CBP6SRzMdgSyXp4AheHxJYlRtTEtupWEGkBcMieQdaEu_Pia2gMBuA10S9o3z9Dcp5TmVFv0fJfP49U0FPIfoox0c5CwIE9meh3kLL0HUTr57Hruo9xmK5e2FsDovZK1EV-pnEckUoeDkRcfJEjqjzgE3xSfuASd-r9YCZr7BJ-ODNRSiCLt5LJ1bhcO_mIjOPZD1lu3gj_PQ8');
